version: 2

models:
  - name: stg_taxi
    description: "Staging model for NYC taxi data"
    columns:
      - name: trip_id
        description: "Primary key for taxi trips"
        tests:
          - unique
          - not_null

  - name: stg_weather
    description: "Staging model for NOAA weather data"
    columns:
      - name: station_id
        description: "Weather station identifier"
      - name: timestamp
        description: "Hourly weather reading timestamp"
