# .pre-commit-config.yaml
repos:
  # --- Code format & style ---
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt
        args: ["-i", "4", "-s"]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks: [ id: black ]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks: [ id: isort ]

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: ["--max-line-length=100", "--extend-ignore=E203,W503"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks: [ id: bandit ]

  # --- Commit-message lint ---
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        stages: [ commit-msg ]          # checks Conventional Commits

  # --- Whitespace / EditorConfig ---
  - repo: https://github.com/editorconfig-checker/editorconfig-checker
    rev: v3.2.1        # latest stable tag as of Apr-2025
    hooks:
      - id: editorconfig-checker
        alias: ec
        exclude: '.*(\.drawio|\.drawio\.svg|\.png|\.jpg|\.jpeg|\.pdf|\.md|\.ipynb|\.sh)$'

