name: 'dbt_nyc_taxi'
version: '1.0.0'

profile: 'dbt_nyc_taxi'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - 'CREATE SCHEMA IF NOT EXISTS "raw";'
  - 'CREATE SCHEMA IF NOT EXISTS "staging";'
  - 'CREATE SCHEMA IF NOT EXISTS "marts";'
  - |
    CREATE TABLE IF NOT EXISTS "raw".yellow_tripdata (
        vendorid                BIGINT,
        tpep_pickup_datetime    TIMESTAMP,
        tpep_dropoff_datetime   TIMESTAMP,
        passenger_count         BIGINT,
        trip_distance           DOUBLE PRECISION,
        ratecodeid              BIGINT,
        store_and_fwd_flag      VARCHAR(1),
        pulocationid            BIGINT,
        dolocationid            BIGINT,
        payment_type            BIGINT,
        fare_amount             DOUBLE PRECISION,
        extra                   DOUBLE PRECISION,
        mta_tax                 DOUBLE PRECISION,
        tip_amount              DOUBLE PRECISION,
        tolls_amount            DOUBLE PRECISION,
        improvement_surcharge   DOUBLE PRECISION,
        total_amount            DOUBLE PRECISION,
        congestion_surcharge    DOUBLE PRECISION,
        airport_fee             DOUBLE PRECISION,
        cbd_congestion_fee      DOUBLE PRECISION
    );
  - |
    CREATE TABLE IF NOT EXISTS "raw".noaa_weather_data (
        ingestion_timestamp     VARCHAR(256),
        source_dataset          VARCHAR(256),
        date                    VARCHAR(256),
        datatype                VARCHAR(256),
        station                 VARCHAR(256),
        value                   NUMERIC(18, 5),
        attributes              VARCHAR(256)
    );


models:
  dbt_nyc_taxi:
    staging:
      +materialized: table
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
