name: 'dbt_nyc_taxi'
version: '1.0.0'

profile: 'dbt_nyc_taxi'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  dbt_nyc_taxi:
    staging:
      +materialized: view
      +schema: staging
