version: 2

sources:
  - name: raw_data
    description: Raw data sources for NYC taxi and weather information
    schema: raw
    tables:
      - name: yellow_tripdata
        description: Raw NYC Yellow Taxi trip records containing pickup/dropoff information, payment details, and trip metrics
        columns:
          - name: vendorid
            description: A code indicating the TPEP provider that provided the record
          - name: tpep_pickup_datetime
            description: The date and time when the meter was engaged
          - name: tpep_dropoff_datetime
            description: The date and time when the meter was disengaged
          - name: ratecodeid
            description: The final rate code in effect at the end of the trip
          - name: pulocationid
            description: TLC Taxi Zone in which the taximeter was engaged
          - name: dolocationid
            description: TLC Taxi Zone in which the taximeter was disengaged
          - name: store_and_fwd_flag
            description: This flag indicates whether the trip record was held in vehicle memory before sending to the vendor
          - name: passenger_count
            description: The number of passengers in the vehicle
          - name: trip_distance
            description: The elapsed trip distance in miles reported by the taximeter
          - name: payment_type
            description: A numeric code signifying how the passenger paid for the trip
          - name: fare_amount
            description: The time-and-distance fare calculated by the meter
          - name: extra
            description: Miscellaneous extras and surcharges
          - name: mta_tax
            description: $0.50 MTA tax that is automatically triggered based on the metered rate in use
          - name: tip_amount
            description: Tip amount – This field is automatically populated for credit card tips
          - name: tolls_amount
            description: Total amount of all tolls paid in trip
          - name: improvement_surcharge
            description: $0.30 improvement surcharge assessed trips at the flag drop
          - name: total_amount
            description: The total amount charged to passengers

      - name: noaa_weather_data
        description: Raw NOAA weather data containing daily weather observations
        columns:
          - name: station
            description: Weather station identifier
          - name: datatype
            description: Type of weather measurement (PRCP, TMAX, TMIN, TAVG)
          - name: value
            description: Measurement value
          - name: attributes
            description: Additional measurement attributes
          - name: date
            description: Date of the weather observation
          - name: source_dataset
            description: Source dataset identifier
